### ISSUE TITLE
img_transform,numpy_params missing

### ISSUE THREAD

**Issue by nive2** [fregu856/CS224n_project#2]
while running extract_img_features_attention.py it assumes that
"  dict numpy_params (containing W_img and b_img taken from the img_transform
  step in a well-performing non-attention model) is placed in coco/data/img_features_attention/transform_params." how to do this?

**Comment by utthaman** [comment]
@fregu856 @nive2  Trying to run the code extract_img_features_attention.py.
Please advice how to get “dict numpy_params”.Which well performing non-attention model should I use.Thanks.

**Comment by fregu856** [comment]
Unfortunately, I don't have access to this file anymore. I apologize for this, and for my terribly late response.

//
Fredrik
